package repository

import (
	"github.com/xia/nextcrm/internal/models"
	"gorm.io/gorm"
)

type UserRepository struct {
	db *gorm.DB
}

func NewUserRepository(db *gorm.DB) *UserRepository {
	return &UserRepository{db: db}
}

// Create creates a new user
func (r *UserRepository) Create(user *models.User) error {
	return r.db.Create(user).Error
}

// FindByID finds a user by ID
func (r *UserRepository) FindByID(id string) (*models.User, error) {
	var user models.User
	err := r.db.First(&user, "id = ?", id).Error
	if err != nil {
		return nil, err
	}
	return &user, nil
}

// FindByAuthCenterUserID finds a user by auth-center user ID
func (r *UserRepository) FindByAuthCenterUserID(authCenterUserID string) (*models.User, error) {
	var user models.User
	err := r.db.Where("auth_center_user_id = ?", authCenterUserID).First(&user).Error
	if err != nil {
		return nil, err
	}
	return &user, nil
}

// FindByEmail finds a user by email
func (r *UserRepository) FindByEmail(email string) (*models.User, error) {
	var user models.User
	err := r.db.Where("email = ?", email).First(&user).Error
	if err != nil {
		return nil, err
	}
	return &user, nil
}

// Update updates a user
func (r *UserRepository) Update(user *models.User) error {
	return r.db.Save(user).Error
}

// Delete soft deletes a user
func (r *UserRepository) Delete(id string) error {
	return r.db.Delete(&models.User{}, "id = ?", id).Error
}

// FindOrCreateByAuthCenter finds or creates a user from auth-center data
func (r *UserRepository) FindOrCreateByAuthCenter(authCenterUserID, unionID, nickname, avatarURL string) (*models.User, error) {
	// Try to find existing user
	user, err := r.FindByAuthCenterUserID(authCenterUserID)
	if err == nil {
		// User exists, update info
		if unionID != "" {
			user.UnionID = &unionID
		}
		if nickname != "" {
			user.Nickname = &nickname
		}
		if avatarURL != "" {
			user.AvatarURL = &avatarURL
		}
		if user.Name == nil {
			user.Name = &nickname
		}
		r.Update(user)
		return user, nil
	}

	// Create new user
	user = &models.User{
		// ID will be auto-generated by database (bigint auto-increment)
		AuthCenterUserID: authCenterUserID,
		UnionID:          &unionID,
		// Email is required by database, use a placeholder if not available
		Email:            &authCenterUserID, // Placeholder: use authCenterUserID as email
		Nickname:         &nickname,
		AvatarURL:        &avatarURL,
		Name:             &nickname,
		Role:             "USER",
		IsActive:         true,
	}

	if err := r.Create(user); err != nil {
		return nil, err
	}

	return user, nil
}

